name: habits_timer
description: Habits timer with Isar
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1

  # --- Isar ---
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # misc
  path_provider: ^2.1.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true